--import Css exposing (..)
--import Css.Elements exposing (..)
--import Css.Namespace exposing (..)
--import Html.CssHelpers
--
--
--type CssClasses = Page | AddButton | SubButton
--
--css =
--    (namespace "example")
--    [
--        Css.Elements.body
--        [
--
--        ],
--      (.) Page [
--        backgroundColor (rgb 200 128 64)
--      ],
--      (.) AddButton [
--        color (hex "CCFFFF")
--      ]
--    ]
--
--
--{ id, class, classList } = Html.CssHelpers.withNamespace "example"
